// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: domain.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
  id, url, user_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, url, user_id
`

type CreateDomainParams struct {
	ID        uuid.UUID
	Url       string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.Url,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
