// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: domains.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (
  id, url, user_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, created_at, updated_at, url, user_id
`

type CreateDomainParams struct {
	ID        uuid.UUID
	Url       string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRowContext(ctx, createDomain,
		arg.ID,
		arg.Url,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, created_at, updated_at, url, user_id FROM domains 
WHERE url = $1
LIMIT 1
`

func (q *Queries) GetDomain(ctx context.Context, url string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, url)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, created_at, updated_at, url, user_id FROM domains 
WHERE user_id = $1
LIMIT 10
`

func (q *Queries) ListDomains(ctx context.Context, userID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Url,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
