// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: domain_sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDomainSession = `-- name: CreateDomainSession :one
INSERT INTO domain_sessions (
  id, event_id, session_start_time, session_end_time, domain_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, event_id, session_start_time, session_end_time, created_at, updated_at, domain_id
`

type CreateDomainSessionParams struct {
	ID               uuid.UUID
	EventID          string
	SessionStartTime time.Time
	SessionEndTime   sql.NullTime
	DomainID         uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) CreateDomainSession(ctx context.Context, arg CreateDomainSessionParams) (DomainSession, error) {
	row := q.db.QueryRowContext(ctx, createDomainSession,
		arg.ID,
		arg.EventID,
		arg.SessionStartTime,
		arg.SessionEndTime,
		arg.DomainID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DomainSession
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SessionStartTime,
		&i.SessionEndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DomainID,
	)
	return i, err
}
