// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Domain struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
	UserID    uuid.UUID
}

type DomainSession struct {
	ID               uuid.UUID
	ClientID         string
	EventID          string
	SessionStartTime time.Time
	SessionEndTime   sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DomainID         uuid.UUID
}

type DomainStat struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Url             string
	Referer         sql.NullString
	DeviceWidth     sql.NullInt32
	UserAgent       sql.NullString
	DomainSessionID uuid.UUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
