version: '3'

services:
  database:
    image: 'postgres:15.4-alpine'

    ports:
      - 5432:5432

    env_file:
      - .env

  cache:
    image: 'redis:7.2.3-alpine'

    ports:
      - '6379:6379'

    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

    env_file:
      - .env
