name: "cd"

on:
  push:
    branches:
      - main

env:
  DOKKU_HOST: ${{ secrets.HOST_IP }}
  DOKKU_USER: server
  DOKKU_APP: ioignition
  DOCKER_IMAGE: ioignition:${{ github.sha }}
  DOKKU_DESTINATION_FOLDER: /home/server/ioignition

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build CSS
        run: npm run build-css

      - name: Build Script
        run: npm run build-script

      - name: Build server
        run: scripts/buildprod.sh

      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DOKKU_HOST >> ~/.ssh/known_hosts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build -t $DOCKER_IMAGE \
            --build-arg DB_URL="${{ secrets.DB_URL }}" \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            --build-arg REDIS_URL=${{ secrets.REDIS_URL }} \
            --build-arg IPINFO_TOKEN=${{ secrets.IPINFO_TOKEN }} \
            . --load
          docker save -o $DOCKER_IMAGE.tar $DOCKER_IMAGE
          scp ./$DOCKER_IMAGE.tar $DOKKU_USER@$DOKKU_HOST:/home/$DOKKU_USER/ioignition/

      - name: Deploy to Dokku
        run: ssh $DOKKU_USER@$DOKKU_HOST "sudo docker load -i $DOKKU_DESTINATION_FOLDER/$DOCKER_IMAGE.tar && sudo dokku git:from-image $DOKKU_APP $DOCKER_IMAGE"

  migrate:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check goose
        run: goose -version

      - name: Run Migrations
        run: ./scripts/migrateup.sh
        env: 
          DB_URL: ${{ secrets.DB_URL}}
