name: "cd"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

env:
  DOKKU_HOST: ${{ secrets.HOST_IP }}
  DOKKU_USER: $${{ secrets.HOST_USER }}
  DOCKER_IMAGE: ioignition:${{ github.sha }}
  DOKKU_DESTINATION_FOLDER: /home/ioignition
  DOKKU_APP_NAME: ${{ secrets.APP_NAME }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DOKKU_HOST >> ~/.ssh/known_hosts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build -t $DOCKER_IMAGE . --load
          docker save -o $DOCKER_IMAGE.tar $DOCKER_IMAGE
          scp ./$DOCKER_IMAGE.tar $DOKKU_USER@$DOKKU_HOST:$DOKKU_DESTINATION_FOLDER/

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Dokku
        run: ssh $DOKKU_USER@$DOKKU_HOST "docker load -i $DOKKU_DESTINATION_FOLDER/$DOCKER_IMAGE.tar && sudo dokku git:from-image $DOKKU_APP_NAME $DOCKER_IMAGE"
