name: 'cd'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{secrets.HOST_IP}}:22/${{secrets.DOKKU_APP_NAME}}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
