name: ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check formatting
        run: test -z $(go fmt ./...)

      - name: Run staticcheck
        run: staticcheck ./...

  security:
    name: security
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.1"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: gosec ./...
