// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Chart(labels []string, data []int, yTitle string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Chart_16eb`,
		Function: `function __templ_Chart_16eb(labels, data, yTitle){const ctx = document.getElementById('largeGraph').getContext('2d');
       const visitorChart = new Chart(ctx, {
         type: 'line',
         data: {
           labels,
           datasets: [{
             data,
             backgroundColor: 'rgba(16, 185, 129, 0.2)', // Emerald-500
             fill: "start",
             borderColor: 'rgba(16, 185, 129)', // Emerald-500
             borderWidth: 2
           }]
         },
         options: {
           plugins: {
             legend: {
               display:false,
             },
           },
           scales: {
             y: {
               beginAtZero: true,
               stepSize: 10, // Adjust this value as needed for suitable intervals
               title: {
                 display: true,
                 text: yTitle,
                 color: '#10b981',
                 font: {
                   size: 16,
                   weight: 'bold',
                   lineHeight: 1.2,
                 },
               },
             },
             x: {
               autoSkip: true,
               maxTicksLimit: 6 // Adjust to control the number of labels on X-axis
              }
           },
           elements: {
             line: {
               tension: 0.4
             }
           }
         }
       });}`,
		Call:       templ.SafeScript(`__templ_Chart_16eb`, labels, data, yTitle),
		CallInline: templ.SafeScriptInline(`__templ_Chart_16eb`, labels, data, yTitle),
	}
}

func Graph(labels []string, data []int, yTitle string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<figure class=\"shadow-lg rounded-2xl bg-zinc-800 p-4\"><canvas id=\"largeGraph\"></canvas>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Chart(labels, data, yTitle).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</figure>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
